# Generated by Django 3.0.6 on 2020-05-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFormVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads_open', models.BooleanField(default=False)),
                ('upload_password', models.CharField(blank=True, max_length=20)),
                ('session_info', models.TextField(blank=True, max_length=1000)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Session')),
            ],
            options={
                'verbose_name': 'Upload form variables',
                'verbose_name_plural': 'Upload form variables',
            },
        ),
    ]
