# Generated by Django 3.0.6 on 2020-05-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadformvars',
            name='session_subsection',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
