# Generated by Django 3.0.6 on 2020-05-15 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('blurb', models.TextField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('info', models.TextField(blank=True, max_length=1000)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='archive/')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Artist')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Session')),
            ],
        ),
        migrations.AddConstraint(
            model_name='audiofile',
            constraint=models.UniqueConstraint(fields=('session', 'name'), name='unique_name_per_session'),
        ),
    ]
