# Generated by Django 3.0.6 on 2020-05-24 22:11

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='session_subsection',
            field=models.CharField(blank=True, default=archive.models.get_session_subsection, max_length=50),
        ),
    ]
