# Generated by Django 3.0.6 on 2020-05-15 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFormVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads_open', models.BooleanField(default=False)),
                ('upload_password', models.CharField(blank=True, max_length=20)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
