# Generated by Django 3.0.6 on 2020-05-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_uploadformvars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadformvars',
            options={'verbose_name_plural': 'Upload form variables'},
        ),
    ]
