# Generated by Django 3.0.8 on 2021-04-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20200525_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='archive.Session'),
        ),
    ]
