# Generated by Django 3.0.8 on 2021-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20210405_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
