# Generated by Django 3.0.6 on 2020-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20200516_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='copyright_issues',
            field=models.BooleanField(default=False),
        ),
    ]
