# Generated by Django 3.0.8 on 2021-04-05 16:17

from django.db import migrations
from mutagen.mp3 import EasyMP3


# In Herokuish environments migrations are performed BEFORE file storage is
# attached, so we can't use the above function. A workaround is to manually go
# into the shell and update all durations by hand. It's not even necessary to
# run the loop below since any .save() operation will make sure that the
# duration is set correctly.

# def backpopulate_duration_field(apps, _):
#     AudioFiles = apps.get_model("archive", "AudioFile")
#     for track in AudioFiles.objects.all():
#         track.duration = round(track.mp3.info.length)
#         track.save(update_fields=["duration"])


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0004_audiofile_duration"),
    ]

    operations = [
        # migrations.RunPython(
        #     backpopulate_duration_field, reverse_code=migrations.RunPython.noop
        # )
    ]
