# Generated by Django 3.0.8 on 2021-04-05 21:10

import archive.MP3Field
import archive.models
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('archive', '0006_auto_20210405_2300'), ('archive', '0007_remove_audiofile_duration')]

    dependencies = [
        ('archive', '0005_auto_20210405_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='data',
            field=archive.MP3Field.MP3Field(upload_to=archive.models.get_upload_path),
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='duration',
        ),
    ]
