# Generated by Django 3.0.6 on 2020-05-16 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_challenge_copyright_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
