# Generated by Django 3.0.6 on 2020-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20200516_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(default=3, unique=True),
            preserve_default=False,
        ),
    ]
