# Generated by Django 3.0.6 on 2020-05-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_challenge_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='session',
        ),
    ]
