# Generated by Django 3.0.6 on 2020-05-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_remove_audiofile_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='audiofile',
            name='unique_name_per_session',
        ),
    ]
