# Generated by Django 3.0.6 on 2020-05-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20200516_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='archive.Session'),
            preserve_default=False,
        ),
    ]
