# Generated by Django 3.0.6 on 2020-05-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20200518_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='session_subsection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
