# Generated by Django 3.0.6 on 2020-05-20 22:42

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_audiofile_session_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='data',
            field=models.FileField(upload_to=archive.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='session_subsection',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
