# Generated by Django 3.0.6 on 2020-05-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_auto_20200521_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFormVars',
        ),
    ]
